reviews:
  namespace: student4-bookinfo-uat
  image: ghcr.io/tian-np/bookinfo-reviews
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8082
  targetPort: 9080
ingress:
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student4/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2

