services:
  ratings:
    build: ./ratings/
    image: ghcr.io/tian-np/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    ports: 
      - "27017:27017"
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings

  details:
    build: ./details/
    image: ghcr.io/tian-np/details:dev
    ports:
      - "8081:9080"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"

  reviews:
    build: ./reviews/
    image: ghcr.io/tian-np/reviews:dev
    ports:
      - "8082:9080"
    environment:
      ENABLE_RATINGS: "true"
      DETAILS_HOSTNAME: "http://details:9080"
      RATINGS_SERVICE: "http://ratings:8080/ratings"

  productpage:
    build: ./productpage/
    image: ghcr.io/tian-np/productpage:dev
    ports:
      - "8083:9080"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
      DETAILS_HOSTNAME: "http://details:9080"
      RATINGS_HOSTNAME: "http://ratings:8080"
      REVIEWS_HOSTNAME: "http://reviews:9080"